# Databricks notebook source


# COMMAND ----------

spark.sql(
    f"""
CREATE TABLE IF NOT EXISTS {CATALOG}.{SCHEMA}.{SOURCE_DATA_FOR_INDEX_TABLE_NAME} (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  path STRING,
  page_content STRING
) TBLPROPERTIES (delta.enableChangeDataFeed = true);
"""
)
